#!/bin/sh

# cleanup
rm -rf obj_dir
rm -f *.vcd

~/Documents/iac/lab0-devtools/tools/attach_usb.sh

# run Verilator to translate Verilog into C++, including C++ testbench
verilator -Wall --cc --trace arc.sv --exe arc_tb.cpp

# build C++ project via make automatically generated by Verilator
make -j -C obj_dir/ -f Varc.mk Varc

# run executable simulation file
echo "\nRunning simulation"
obj_dir/Varc
echo "\nSimulation completed"

